apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openbao-tls
  namespace: openbao
spec:
  secretName: openbao-tls
  duration: 8760h # 1 year
  renewBefore: 720h # 30 days
  subject:
    organizations:
      - OpenBao
  commonName: openbao.openbao.svc
  dnsNames:
    - localhost
    - openbao
    - openbao.openbao
    - openbao.openbao.svc
    - openbao.openbao.svc.cluster.local
    - openbao-0.openbao-internal
    - openbao-1.openbao-internal
    - openbao-2.openbao-internal
    - openbao-0.openbao-internal.openbao.svc.cluster.local
    - openbao-1.openbao-internal.openbao.svc.cluster.local
    - openbao-2.openbao-internal.openbao.svc.cluster.local
  ipAddresses:
    - 127.0.0.1
    - 10.1.1.12
    - 192.168.49.20
  issuerRef:
    name: openbao-ca-issuer
    kind: Issuer
