apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: root-tls-issuer
spec:
  selfSigned: {}
--- 
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: openbao-ca-issuer
spec:
  ca:
    secretName: openbao-ca-secret  
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openbao-ca-cert
spec:
  isCA: true
  commonName: openbao-ca
  secretName: openbao-ca-secret
  duration: 87600h # 10 years
  renewBefore: 720h # 30 days
  privateKey:
    algorithm: RSA
    size: 4096
  subject:
    organizationalUnits:
      - "OpenBao CA"
    organizations:
      - "An Org"
  issuerRef:
    name: root-tls-issuer
    kind: Issuer
---

