apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: watcher-nats-credential
  namespace: nats 
spec:
  isCA: false
  duration: "6h"
  renewBefore: "3h"
  subject:
    organizations:
    - watcher
  privateKey:
    algorithm: RSA
    size: 4096
    rotationPolicy: Always
  commonName: watcher
  dnsNames:
    - localhost
    - watcher
    - watcher-service
    - watcher-service.nats.svc.cluster.local
  ipAddresses:
    - 127.0.0.1
    - 10.1.1.12
  secretName: watcher-nats-credential
  issuerRef:
    name: watcher-tls-issuer
