---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: watcher-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "update", "patch", "create"] 
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: ["cert-manager.io"]
  resources: ["certificates"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["get", "list", "watch", "update", "patch"] 
   
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: watcher-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: watcher-role
subjects:
- kind: ServiceAccount
  name: watcher-sa
