apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: metadata-role
  namespace: metadata
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: metadata-role-binding
  namespace: metadata
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: metadata-role
subjects:
- kind: ServiceAccount
  name: metadata-sa
  namespace: metadata
