# PersistentVolumeClaim for secret storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-secrets-pvc
  labels:
    app: metadata-svc
    component: shared-secrets
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard  # Adjust based on your cluster's storage classes

---
# PersistentVolumeClaim for client certs
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: client-certs-pvc
  labels:
    app: metadata-svc
#    component: shared-secrets
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard  # Adjust based on your cluster's storage classes

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bao-agent-token-pvc
  labels:
    app: metadata-svc
    component: vault-token
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi  # More than enough for a few small files
  storageClassName: standard  # Adjust if using a different storage class

