apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-secrets-pvc
  namespace: metadata
  labels:
    app: metadata
    component: shared-secrets
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: client-certs-pvc
  namespace: metadata
  labels:
    app: metadata
    component: client-certs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bao-agent-token-pvc
  namespace: metadata
  labels:
    app: metadata
    component: vault-token
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
